Lesson 6 alexandra nechita
mariuspodean/NATIONAL-PYTHON-01 pull request #15
Opened 2020-10-04 08:20 UTC by alenechita

2020-10-07 06:32 UTC, Liitle requested changes
Felicitari pentur tema 🎉 🎉. Ma bucur ca ai adaugat mai multe variante pentru rezolvare. Am mentionat mai jos cateva posibile imbunatatiri. 

Iti recomand sa pui fiecare varianta de solutie intr-un fisier separat ca sa fie functionale. De cele mai multe ori codul comentat trebuie sters din varianta finala a programului deoarece nu functioneaza si doar incarca (vizual) fisierul. Te incurajez sa faci mai multe variante si la urmatoarele teme

Felicitari inca o data

2020-10-07 06:32 UTC, Liitle commented on lesson_6/alexandra_nechita/6thHomework_Python.py
> +#Varianta 1 - with no use of the description list
Imi place varianta asta. Uita-te putin peste 'enumerate()' https://docs.python.org/3/library/functions.html#enumerate . Poate simplifica codul din `Varianta 1`

2020-10-07 06:32 UTC, Liitle commented on lesson_6/alexandra_nechita/6thHomework_Python.py
> +#         for index in reversed(coverage):
de ce a fost nevoie de `reversed` aici ? 😄

2020-10-07 06:32 UTC, Liitle commented on lesson_6/alexandra_nechita/6thHomework_Python.py
> +        year_index=len(description[1])-1
Solutia asta mi se pare cea mai ok, sa iterezi prin 2 liste in acelasi timp. Avem in python o varianta mai usoara decat sa incrementam manual indexul. Uita-te peste `zip()` https://docs.python.org/3/library/functions.html#zip. `description[1]` si `coverage` au aceisi lungime si pot fi iterate simultan cu `zip`

2020-10-07 06:32 UTC, Liitle commented on lesson_6/alexandra_nechita/6thHomework_Python.py
> +# Varianta 1 - where we skip non-numeric data for coverage
Imi place mai mult varianta 1 in cazul `perform_average`.  O ideie ar fi sa separam partea de clean-up ( inlocuirea spatilor  si a ': ') intr-o functie separata pe care o chemam in `perform_average` si ulterior sa folosim `sum()` https://docs.python.org/3/library/functions.html#sum pentru suma.

2020-10-12 06:39 UTC, Liitle commented
salut @alenechita, ai reusit sa te uiti peste comentarii? pot sa fac merge la PR sau vrei sa mai faci modificari ?

2020-10-12 12:45 UTC, alenechita commented
Salut @Liitle, m-am uitat peste comentarii, dar nu am reusit sa fac modificarile inca. Cel mai devreme, as putea face modificari in weekend, daca nu e prea tarziu. Daca e prea tarziu, atunci poti face merge. Thanks

2020-10-12 14:43 UTC, Liitle commented
Nu ne grabim, cand poti tu 😄

2020-10-25 09:15 UTC, mariuspodean commented
@alenechita @Liitle  Any updates on this?

2020-10-25 09:21 UTC, alenechita commented
I didn't have time to work on it, I will probably update it next weekend. Thanks

2020-11-30 16:36 UTC, alenechita reviewed
@Liitle I made the suggested changes

2020-12-07 07:14 UTC, Liitle approved these changes
Nice, merging

2020-12-07 07:15 UTC, merged