Lesson 6 victor lupsa
mariuspodean/NATIONAL-PYTHON-01 pull request #16
Opened 2020-10-04 13:51 UTC by ViktorL77

Salut! Sper ca e bine cum am facut

2020-10-06 20:54 UTC, Liitle requested changes
Felicitari pentru tema 🎉 🎉 , imi place implementarea. Am lasat mai jos cateva sugesti de posibile imbunatatiri.

Legat de structura fisierelor ai adaugat un fisier cu rezolvarea temei de lesson_6 in folderul lesson_4. pe branchul asta cu lesson-6-victor-lupsa poti sa stergi folderul cu lesson_4 ( dupaia git add si git commit)

Felicitari inca o data

2020-10-06 20:54 UTC, Liitle commented on lesson_6/victor_lupsa/Lesson_6_lupsa_victor.py
> +    for x in raw_data:
Aici poti sa incerci tuple unpaking in for. Asta o sa te scape de indexi de genu `x[1][i]` sau `x[0]`. Incearca 
` for country, data in raw_data` country o sa fie `x[0]` si data o sa fie `x[1]`

2020-10-06 20:54 UTC, Liitle commented on lesson_6/victor_lupsa/Lesson_6_lupsa_victor.py
> +        i = 0
nu ii nevoie sa incrementezi manual i-ul poti itera prin ambele liste in acelasi timp folosind `zip()` https://docs.python.org/3/library/functions.html#zip. Incearca sa folosesti `zip(description[1],x[1])` in loc de doar `description[1]` in for

2020-10-06 20:54 UTC, Liitle commented on lesson_6/victor_lupsa/Lesson_6_lupsa_victor.py
> +        entry_list = []
poti sa muti `entry_list = []` pe linia 52 si nu o sa mai fie nevoie sa cureti lista la final o initializezi goala inainte de fiecare iteratie. Daca faci modificarea nu o sa mai ai nevoie de `entry_list = []` pe linia 50

2020-10-06 20:54 UTC, Liitle commented on lesson_6/victor_lupsa/Lesson_6_lupsa_victor.py
> +print('----'*20)
This is nice

2020-10-06 20:54 UTC, Liitle commented on lesson_6/victor_lupsa/Lesson_6_lupsa_victor.py
> +    for x in country_data:
putem evita for-ul daca folosim `sum()` https://docs.python.org/3/library/functions.html#sum

2020-10-11 10:20 UTC, Ioan-E reviewed
Scuze de intarzierea review-ului. Mie imi e clar ce face si inteleg cum functioneaza deci codul sigur e usor de citit. Mai departe nu am nimic de adaugat fata de ce a zis deja George. Felicitari!

2020-10-12 06:40 UTC, Liitle commented
salut @ViktorL77 , ai reusit sa te uiti peste comentarii? pot sa fac merge sau mai vrei sa faci modificari?

2020-10-25 09:16 UTC, mariuspodean commented
@ViktorL77 @Liitle Any updates on this PR?

2020-11-02 06:59 UTC, Liitle commented
@ViktorL77 am facut merge la PR, daca doresti sa faci modificari la fisierele de lesson_6 bazat pe feedbakul de mai sus, te rog sa deschzi un PR nou 😄

2020-11-02 06:59 UTC, merged