Lesson 6 matei alexandru
mariuspodean/NATIONAL-PYTHON-01 pull request #20
Opened 2020-10-06 15:06 UTC by MateiAlexandru97

2020-10-06 16:59 UTC, Liitle commented
salut @MateiAlexandru97 , commitul nu contine modificarile cu tema. Cel mai probabil ai uitat sa adaugi fisierele pentru commit cu `git add`. Dupa ce ai salvat fisierul ruleaza comanda git add urmata de numele fisierului dupaia ruleaza comanda `git commit -m "mesajul de commit"`

2020-10-19 06:30 UTC, Liitle requested changes
Super fain, felicitari. Imi place mult cum ai procesat datele. Am lasat un comentariu legate de `get_country_data`, faptul ca procesarea datelor este facuta bine la `get_country_data` poate sa aiba o logica mai simpla

2020-10-19 06:30 UTC, Liitle commented on lesson_6.py
> +    dataset_data_to_process = {
this is really nice, goodjob

2020-10-19 06:30 UTC, Liitle commented on lesson_6.py
> +    for i in range(len(dataset_get_country_data[f"{country}"])):
aici nu cred ca este necesara procesarea asta, in datasetul procesat mai sus ai deja tarile ca si chei de dictionar. 

`dataset_get_country_data[f"{country}"]` aici f stringul nu este necesar. Pentru transformarea in string folosim `str()` dar  aici country este deja string.

Incearca sa simplifici codul in jurul valori pe care o ai in `dataset_get_country_data[country]`

2020-10-25 09:17 UTC, mariuspodean commented
@MateiAlexandru97  Any updates on this PR?

2020-11-02 07:01 UTC, Liitle commented
Closing PR and keeping the branch

2020-11-02 07:01 UTC, closed without merging