My homework for decorators
mariuspodean/NATIONAL-PYTHON-01 pull request #25
Opened 2020-10-11 12:54 UTC by alenechita

2020-10-19 06:54 UTC, Liitle requested changes
Super fain! 🥳 Am mentionat cateva posibile modificari.

2020-10-19 06:54 UTC, Liitle commented on alexandra_nechita/7th.2.Python_Homework.py
> +        return print(divide(first_number, second_number))
daca folosim print functia o sa returneze un string in loc de `int` o functie care face o impartire ne asteptam tot timpul sa returneze un `int` sau un `float`. Aici poti sa returnezi direct `divide(first_number, second_number)`

2020-10-19 06:54 UTC, Liitle commented on alexandra_nechita/7th.3.Python_Homework.py
> +      print ('I am a useless function')
Saraca functie.  Glumesc 😄 

Aici e bine sa returnezi functia primita ca sa ii pastram functionalitatea. Inregistram numele functiei si returnam `func`

Rezolvarea din punctul de vedere al decoratorilor este corecta

2020-10-19 06:55 UTC, Liitle commented
Adaugi te rog folderul tau intr-un folder `lesson_7`

2020-10-25 09:18 UTC, mariuspodean commented
@alenechita Any updates on this PR?

2020-10-25 09:20 UTC, alenechita commented
Not yet, I will make some changes but not this week. I hope I will work on it next weekend. Thanks

2020-11-02 07:02 UTC, merged