Lesson 7 ioan juglea
mariuspodean/NATIONAL-PYTHON-01 pull request #26
Opened 2020-10-11 13:10 UTC by jugleaioan

2020-10-19 06:48 UTC, Liitle requested changes
Super faina tema 🥳 Am lasat mai jos un comentariu cu o mica modificare

2020-10-19 06:48 UTC, Liitle commented on Lesson-7-Ioan-Juglea/Homework.py
> +    def inner_func(name):
aici nu este nevoie de un `inner_func` deoarece nu faci nicio modificare doar returnezi functia. Poti sa returnezi direct `func` si o sa functioneze la fel

2020-10-25 09:19 UTC, mariuspodean commented
@jugleaioan Any updates on this PR?

2020-11-02 07:02 UTC, Liitle approved these changes

2020-11-02 07:03 UTC, merged