Lesson 7 oana agafitei
mariuspodean/NATIONAL-PYTHON-01 pull request #28
Opened 2020-10-11 16:31 UTC by OanaA-hub

Homework 7 solution

2020-10-19 07:08 UTC, Liitle requested changes
super tema 🥳 am lasat cateva comentarii mai jos

2020-10-19 07:08 UTC, Liitle commented on lesson_7/oana_agafitei/lesson7_decorators_homework.py
> +'''def uppercase(name):
pentru a comenta mai multe linii de cod poti sa le selectezi si sa apesi `ctrl + /`. In cazul asta poti decomenta functia este corecta

2020-10-19 07:08 UTC, Liitle commented on lesson_7/oana_agafitei/lesson7_decorators_homework.py
> +    def wrapper(input):
Este corecta rezolvarea. O varianta mai scurta ar fi sa returnezi direct `name(input).upper()` 

O alta posibila imbunatatire ar fi numele variabilelor `name` este functia decorata nu neaparat un nume

2020-10-19 07:08 UTC, Liitle commented on lesson_7/oana_agafitei/lesson7_decorators_homework.py
> +    global print_registry
in cazul acesta nu avem nevoie de `global` print_registry este deja intr-un scop superior si poate fi folosit

2020-10-19 07:08 UTC, Liitle commented on lesson_7/oana_agafitei/lesson7_decorators_homework.py
> +    def inside(name):
aici nu este nevoie de `inside` daca nu modifici `func` poti sa returnezi direct `func`

2020-10-25 09:20 UTC, mariuspodean commented
@OanaA-hub Any updates on this PR?
This PR should go against lesson 7 and not master ;)

2020-11-02 07:04 UTC, Liitle commented
Closing this PR, we have a new one for same homework https://github.com/mariuspodean/NATIONAL-PYTHON-01/pull/33

2020-11-02 07:04 UTC, closed without merging