8thHomework_Python
mariuspodean/NATIONAL-PYTHON-01 pull request #36
Opened 2020-10-25 18:52 UTC by alenechita

Classes Inheritance part - feedback needed

2020-11-02 07:59 UTC, Liitle requested changes
Super tema, am adaugat cateva posibile imbunattiri legate de aranjarea codului

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +        if (date.today() - date(self.admission_date[0],self.admission_date[1], self.admission_date[2])).days == days_of_hospitalization:
ca sa fie mai usor de citit poti muta `date.today() - date(self.admission_date[0],self.admission_date[1], self.admission_date[2])).days` intr-o variabila separata

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +        elif (date.today() - date(self.admission_date[0],self.admission_date[1], self.admission_date[2])).days < days_of_hospitalization:
cum ziceam mai sus, o sa poti refolosi variabila in toate `if`-urile

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +    def is_dischargeable (self, days_of_hospitalization):
genu de metode care incep cu `is_` este recomandat sa returneze `True` sau `False`  si partea de mesaje sa fie cupsa intr-o alta metoda care se foloseste de metoda `is_dischargeable`

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +        return 'Good is not enough \n'
I like this one 😄

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +            birth_year = 1900 + cnp_as_list[1]*10 + cnp_as_list[2]
poti sa fragmentezi cnp-u folsind `slice()`
```
cnp = '1940304...'
year = slice(1,3)
month = slice(3,5)

print(cnp[year])
print(cnp[month])
```
abordarea asta o sa simplifice mult codul

2020-11-02 07:59 UTC, Liitle commented on lesson_8/alexandra_nechita/8thHomework_Python - Classes Inheritance.py
> +        if cnp_as_list[0] == 1 or cnp_as_list[0] == 2:
aici ma gandesc ca vrei sa verifici daca cnp-ul este valid. Din cauza ca structura cnp-ului din Romania ii cunoscuta in principal de romani 😄 aici merge o metoda extra de genu 
```
def is_cnp_valid(self):
    return cnp_as_list[0] == 1 or cnp_as_list[0] == 2
```
sau 

```
def is_cnp_valid(self):
    # 1 and 5 -> male
    #  2 and 6 -> female
    return cnp_as_list[0] in [1,2,5,6]
```

2020-11-30 16:43 UTC, alenechita commented
@Liitle am pus update-urile necesare

2020-12-07 07:16 UTC, Liitle approved these changes

2020-12-07 07:16 UTC, merged